name: CI
on:
  push:
  pull_request:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          cd python
          python -m pip install --upgrade pip
          pip install pytest
          export PYTHONPATH=$PWD          # ← 추가
          pytest -q

  cpp-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure & Build (CMake)
        run: |
          cd cpp
          cmake -S . -B build
          cmake --build build --config Release
